export const EDITABLE_LIST_STEP_NAMES = {
  EXISTING_ITEM: "EDITABLE_LIST_EXISTING_ITEM",
  ADD_NEW_ITEM: "EDITABLE_LIST_NEW_ITEM",
}

export const SEARCHABLE_INPUT_STEP_NAMES = {
  NEW_BUTTON: "SEARCHABLE_INPUT_DROPDOWN_NEW_BUTTON",
  OLD_BUTTON: "SEARCHABLE_INPUT_DROPDOWN_OLD_BUTTON",
  INPUT_AND_SAVE: "SEARCHABLE_INPUT_DROPDOWN_INPUT_AND_SAVE",
  DROPDOWN_BUTTON: "SEARCHABLE_INPUT_DROPDOWN_DROPDOWN_BUTTON",
}

export const SEARCH_BOX_STEP_NAMES = {
  SEARCH_BOX: "SEARCH_BOX",
}